# Generated by Django 3.1.7 on 2021-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('numlist', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='winnumber',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='winnumber',
            name='no',
            field=models.CharField(default='', max_length=4),
        ),
    ]
