# Generated by Django 3.1.7 on 2021-08-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winnum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinNumber',
            new_name='Winnum',
        ),
    ]
