# Generated by Django 3.2.2 on 2021-05-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynumlist', '0003_auto_20210515_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynumlist',
            name='usernum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
