# Generated by Django 3.2.2 on 2021-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynumlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='numlist',
            new_name='numlists',
        ),
    ]
