# Generated by Django 3.2.2 on 2021-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynumlist', '0002_rename_numlist_numlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynumlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=4)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='numlists',
        ),
    ]
