# Generated by Django 3.2.2 on 2021-05-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynumlist', '0004_mynumlist_usernum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynumlist',
            old_name='usernum',
            new_name='username',
        ),
    ]
